Python 3
cedir/web pull request #157
Opened 2020-09-17 13:45 UTC by QPotato

# Python 3: 2to3 y algunos mas

Esta es la definitiva. Al mergear esta se reinstala el ENV con Python 3.

## Cambios en esta PR

- Cambios automaticos de 2to3
- Saque unos Context en turnos que parece que ya no andan
- el encoding de security/encryption pasa a bytes()
- algunos tests ahora necesitan mas fixtures para respetar restricciones
de foreign key
- Versiones de librerias para que ande pyafipws (WiP)
- En algun momento, el requirements-travis.txt paso a ser igual al requirements.txt, asi que borre el primero. Por supuesto, travis pasa a usar Python 3.

## Estado de la PR

- WiP. La voy creando para que vayan viendo de que se trata.
- Los unit test ya corren todos.
- En los integration tests, pyafipws tiene un problema de compatibilidad que todavia estoy rastreando, cuando queremos emitir una factura.
- Una vez resuelto eso, vamos a testear manualmente en staging.

## Migrations

En todas cambia el codigo, pero no hay que correrlas ni nada.

2020-09-17 20:17 UTC, walterbrunetti approved these changes
![altoguiso](https://user-images.githubusercontent.com/2583662/93523543-93540380-f909-11ea-83fc-9f3c6677a5f4.jpg)
 alto PR ameo

2020-09-18 11:08 UTC, QPotato commented on comprobante/imprimir.py
> -    'mensaje_leyenda_honorarios': u'Este comprobante contiene honorarios por cuenta y órden de médicos.',
Esto hay que testearlo manualmente

2020-09-18 11:08 UTC, QPotato commented on comprobante/informe_ventas.py
testear manualmente

2020-09-18 11:08 UTC, QPotato commented on turno/views.py
> -    c = Context({
Esto es un cambio manual

2020-09-18 11:08 UTC, QPotato commented on security/encryption.py
> +    return random_letter + base64.urlsafe_b64encode(bytes(str(key), 'ascii'))
Cambio manual

2020-09-21 03:26 UTC, DanielLezcano727 requested changes
Ademas de los comentarios que te puse, fijate que ademas travis tira error en el pylint y en los tests aparece (esto tanto en local como en travis) un warning sobre pagination.

2020-09-21 03:26 UTC, DanielLezcano727 commented on medico/views.py
> +    if not request.user.is_authenticated:
Sobre esto, vi que se cambia en todos lados exceptuando este archivo:
https://github.com/cedir/web/blob/master/security/permissions/drf.py#L16
Creo que es algo de django rest framework, pero creo que estaria copado averiguar si sigue andando por mas que se este llamando a la funcion.

2020-09-21 03:26 UTC, DanielLezcano727 commented on scripts/tool_testear_afip_contra_webservice.py
> +    print((factura.cae))
Esto no se por que se hace pero lo vi en varias partes de la aplicacion. Los dobles parentesis lo hace por algo en particular?

2020-09-21 11:23 UTC, QPotato commented on medico/views.py
> +    if not request.user.is_authenticated:
Esta deprecado, para borrarlo en django 2 creo. Si lo mantenes tira un warning.

2020-09-21 11:24 UTC, QPotato commented on contenidos/views.py
> +import urllib.request, urllib.error, urllib.parse
Si, cambiaron urllib y lo dividieron. Ahora reviso como afecta al mail.

2020-09-21 11:25 UTC, QPotato commented on scripts/tool_testear_afip_contra_webservice.py
> +    print((factura.cae))
`print` antes era una palabra reservada, un comando tipo como `if`. En python 3 es una funcion asi que necesita si o si que lo que sigue esté entre parentesis. Medio vago no checkea que ya los tiene, pero bueno :P

2020-09-21 14:00 UTC, DanielLezcano727 approved these changes
Quedo genial!! Cuando este andando lo de poder enviar mails ya puede ir mergeado

2020-09-21 22:39 UTC, merged