caja crear movimientos caja
cedir/web pull request #188
Opened 2021-02-22 15:21 UTC by Crussado

# Caja crear movimientos caja

Qué cambios incorporas?
Se agrega la funcionalidad de agregar movimientos.

## Estado de la PR
Lista pero faltan hacer tests.

## Migrations
No.

2021-03-09 12:58 UTC, DanielLezcano727 commented on caja/views.py
> +                movimiento_caja = MovimientoCaja(
Creo que en vez de guardar las variables podrias hacer algo como 
```python
for movimiento in movimientos:
    monto_acumulado += monto
    movimiento_caja = MovimientoCaja({**movimiento, monto_acumulado = monto_acumulado, estudio=estudio})
    movimiento_caja.is_valid(raise_exception=True)
    movimiento_caja.save()
```

2021-03-09 12:58 UTC, DanielLezcano727 commented on caja/views.py
> +                movimiento_caja = MovimientoCaja(
Acordate de hacer el is_valid antes de guardarlo porque creo que no te deja sino

2021-03-09 12:58 UTC, DanielLezcano727 commented on caja/serializers.py
> +        fields = ('hora', 'concepto', 'tipo', 'medico', 'monto')
Quizas podrias agregarle algunas validaciones a las cosas. Como que el monto sea positivo, que el medico exista (no se si estas recibiendo un nombre o un id, pero fijarte con eso), cosas asi

2021-03-09 12:58 UTC, DanielLezcano727 commented on caja/views.py
> +                hora = movimiento['hora']
Creo que la hora deberia generarse en el backend

2021-03-09 12:58 UTC, DanielLezcano727 commented on caja/views.py
> +            response = JsonResponse({}, status=status.HTTP_200_OK)
Segun travis dice que no importaste el status, despues fijate eso :guide_dog:

2021-04-12 19:32 UTC, DanielLezcano727 approved these changes

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/serializers.py
> +            tipo = tipo, medico = medico, monto = monto, concepto = concepto, monto_acumulado = monto_acumulado)
Si solo guardas los valores para esta linea, creo que podes hacer algo como
```python
movimiento = MovimientoCaja.objects.create(fecha=fecha, hora=hora, estudio=estudio, **movimiento)
```

El **objeto "saca" las llaves del objeto
El Model.objects.create() crea el objeto y tambien lo guarda en la base de datos

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/serializers.py
> +            tipo = tipo, medico = medico, monto = monto, concepto = concepto, monto_acumulado = monto_acumulado)
Quizas hasta podrias hacerlo utilizando listas por comprension.
```python

 return [MovimientoCaja.objects.create(fecha=fecha, hora=hora, estudio=estudio, **movimiento) for movimiento in movimientos]

```

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +        'anestesistas.json', 'presentaciones.json', 'comprobantes.json', 'estudios.json', 'medicamentos.json']
Ojo que escribiste medicos.json dos veces.
El de presentaciones, comprobantes y medicamentos los necesitas?

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +        ultimo_monto = MovimientoCaja.objects.all().last().monto_acumulado
En todos los anteriores, el all() no es necesario si vas a ejecutar otra query despues. Es decir, podes hacer .first(), .last() sin .all() antes.
Si no me equivoco, el .all() es para cuando necesitas devolver todos los objetos

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +        cantidad_movimientos = len(MovimientoCaja.objects.all())
Aca podes hacer directamente `MovimientoCaja.objects.count()`

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +        cantidad_movimientos = len(MovimientoCaja.objects.all())
Ojo que lo hiciste en varios lugares

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +            }
Estoy viendo que mas o menos usas siempre el mismo movimiento (o por lo menos, el mismo esquema). Quizas podrias guardarlo en self dentro de la funcion setUp e ir copiando el objeto e ir sobreescribiendo o borrando lo que no necesites para el test que pensas probar. Me parece que va a quedar mas limpio.

Si llegas a hacer eso, te recomiendo crear el objeto datos completo, con dos movimientos (o los que hayas hecho tests o vayas a hacer)

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +        assert nuevo_movimiento.medico == Medico.objects.all().first()
Estos datos creo que los podrias comparar con los ids del principio de la funcion en vez de hacer otra query mas

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +        montos = '10.00', '-1.99'
Tanto como aca como la linea 58, siempre que vayas a hacer una tupla ponele los () para legibilidad ;)

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +        # print(response.content)
:exclamation::question::exclamation::question::exclamation::question: :anger::collision:

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/tests.py
> +            assert cantidad_movimientos == len(MovimientoCaja.objects.all())
Tambien me pareceria bueno crear un test que pruebe con movimientos con monto 0, y monto negativo para verificar que no hay ningun problema

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/views.py
> +    }
Creo que esto no es necesario. El
```python
serializers = {
create: serializer,
update: serializer,
...
}
```
solo se pone cuando se modifica la funcion `get_serializer_class`, ya que ingresa a ese serializer sin pasar por ninguna funcion escrita por nosotros.
De todas formas, estaria bueno que lo verifiques

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/views.py
> +    #     return response
Yo imagino que todo esto lo vas a borrar, pero te dejo el comentario por las dudas

2021-04-12 19:32 UTC, DanielLezcano727 commented on caja/serializers.py
> +        return value
Aunque esto capaz lo estas haciendo al hacer pk=value? :thinking:

2021-04-12 20:59 UTC, Crussado commented on caja/serializers.py
> +    tipo_id = serializers.IntegerField()
Lo pongo, pero hasta donde habia visto no cambiaba el funcionamiento

2021-04-15 15:01 UTC, Crussado commented on caja/serializers.py
> +        return value
Creo que lo hace al hacer pk=value

2021-04-15 15:08 UTC, Crussado commented on caja/serializers.py
> +            tipo = tipo, medico = medico, monto = monto, concepto = concepto, monto_acumulado = monto_acumulado)
Con lo que pusiste de desempaquetar movimiento, no podría sacar el monto acumulado salvo que lo haga aparte, sin embargo ademas de eso, movimiento tiene los campos "medico_id", "tipo_id" por ejemplo, y no son los que MovimientoCaja necesita. Tal vez esto ultimo se resuelve con el comentario anterior que no entendí ;).

2021-04-15 15:12 UTC, Crussado commented on caja/tests.py
> +        'anestesistas.json', 'presentaciones.json', 'comprobantes.json', 'estudios.json', 'medicamentos.json']
Creo que aunque no los use yo directamente, tal vez estudio necesita cargar algunos medicamentos por ejemplo, y si no los agrego tiraria un error.

2021-04-15 16:23 UTC, Crussado commented on caja/tests.py
> +            assert cantidad_movimientos == len(MovimientoCaja.objects.all())
No entiendo bien que queres y el porque.

2021-04-27 18:55 UTC, DanielLezcano727 requested changes

2021-04-27 18:55 UTC, DanielLezcano727 commented on caja/serializers.py
> +            movimiento = MovimientoCaja.objects.create(estudio = estudio, user = user, tipo = tipo,
Te fijaste si podes hacer MovimientoCaja.objects.create(**movimiento) y agregandole la info que consideres necesaria (como monto_acumulado)

2021-04-27 18:55 UTC, DanielLezcano727 commented on caja/tests.py
> +
Haceme acordar que te hable de esto ;)

2021-04-27 18:55 UTC, DanielLezcano727 commented on caja/tests.py
> +    def test_crear_movimientos_falla_monto_nulo(self):
Nooo, esto deberia andar :cry:

2021-04-27 18:55 UTC, DanielLezcano727 commented on caja/tests.py
> +        assert self.cantidad_movimientos == MovimientoCaja.objects.count()
Quizas despues de esto deberias verificar que si le pones el tipo bien se crea bien. De esa forma sabes que lo unico que fallo en todos los anteriores fue lo que deberia fallar

2021-04-27 18:55 UTC, DanielLezcano727 commented on caja/views.py
> +            if not request.user.is_authenticated:
Me parece que no hace falta chequear esto, no? Ya lo deberia hacer internamente django con el token

2021-04-27 20:25 UTC, Crussado commented on caja/serializers.py
> +from pytz import timezone
Igual no lo uso, ni a timezone, ni datetime, los quito

2021-04-27 21:58 UTC, DanielLezcano727 approved these changes

2021-04-28 12:56 UTC, merged